search:
  query: "(health OR healthcare OR medical OR medicine) in:name,description,readme is:public stars:>15"
  topics:
    - robotics
    - robot
    - surgical-robot
    - teleoperation
    - ros
    - manipulation
    - exoskeleton
    - digital-therapeutics
    - tinyml
    - on-device
    - edge-ai
    - federated-learning
    - privacy
    - synthetic-data
    - pocus
    - handheld-ultrasound
    - clinical-scribe
    - digital-twin
    - nextflow
    - wdl
    - vr
    - ar
  languages:
    - Python
    - R
    - Julia
    - Java
    - C#
    - C
    - C++
    - Rust
    - Go
    - JavaScript
    - TypeScript
    - PHP
    - Scala
    - Kotlin
    - Swift
    - Objective-C
    - Ruby
    - MATLAB
    - Shell
    - SQL
    - Dart
    - Elixir
    - Erlang
    - Jupyter Notebook

  # New optional settings to diversify discovery (all are backward compatible)
  # Global defaults applied unless overridden per-strategy
  sort: updated          # one of: stars | forks | help-wanted-issues | updated | created
  order: desc            # asc | desc
  pushed_within_days: 30 # include only repos pushed in the last N days when used
  created_within_days: 14
  exclude_forks: true
  exclude_archived: true
  orgs: []               # e.g., ["HL7", "OHDSI", "Project-MONAI"]
  users: []              # e.g., ["some-user"]

  # When provided, each strategy runs and results are merged (with de-dup)
  strategies:
    - name: recent_updates
      use: pushed_within_days
      sort: updated
      order: desc
    - name: newly_created
      use: created_within_days
      sort: created
      order: desc
    - name: high_stars
      query_extra: "stars:>100"
      sort: stars
      order: desc

weights:
  stars: 0.3
  forks: 0.2
  open_issues: -0.1
  prs: 0.2
  discussions: 0.15
  license:
    MIT: 50
    Apache-2.0: 50
    GPL-3.0: 30
    none: -100
  # Optional additional signals
  contributors: 0.3
  recency_decay: 2.0

output:
  file: "result/healthtech-tools-{date}.md"
  latest: "result/healthtech-tools.md"
  categories:
    - AI Diagnostics
    - Telemedicine
    - EHR & Clinical Systems
    - Imaging & Radiology
    - Wearables & Remote Monitoring
    - Public Health & Epidemiology
    - Genomics & Precision Medicine
    - Mental Health
    - Patient Engagement & Scheduling
    - NLP & Clinical Text
    - FHIR & Interoperability
    - Data Platforms & ETL
    - Robotics & Surgical Systems
    - Digital Therapeutics
    - Privacy & Synthetic Data
    - Digital Twins & Simulation
    - Edge & Mobile Health AI
    - AR/VR & Training
  category_keywords:
    "AI Diagnostics":
      - ai
      - artificial intelligence
      - machine learning
      - deep learning
      - foundation model
      - large language model
      - llm
      - vision-language model
      - vlm
      - multimodal
      - multi-modal
      - vqa
      - retrieval augmented generation
      - retrieval-augmented generation
      - rag
      - agent
      - agentic
      - medical agent
      - clinical agent
      - transformer
      - attention
      - self-attention
      - graph neural network
      - gnn
      - graph-based attention
      - gat
      - gcn
      - graph attention network
      - diagnosis model
      - medical reasoning
      - clinical decision support
    Telemedicine:
      - telecare
      - remote visit
      - teleconsultation
      - teleconsult
      - video visit
      - virtual visit
      - remote triage
      - remote patient visit
    "Imaging & Radiology":
      - radiomics
      - dicomweb
      - radiography
      - mammography
      - pet-ct
      - segmentation
      - registration
      - image reconstruction
      - medical image analysis
    "EHR & Clinical Systems":
      - ehr system
      - emr system
      - medical record
      - clinical decision support
      - order entry
      - cpoe
      - hl7 v2
      - cds hooks
      - liss
      - ris
      - his
    "NLP & Clinical Text":
      - clinical nlp
      - de-id
      - annotation
      - deidentification
      - entity extraction
      - concept extraction
      - text classification
      - note parsing
      - LLM
      - transformer
      - bert
      - medspaCy
      - cTAKES
      - negation detection
      - assertion status
    "FHIR & Interoperability":
      - fhir server
      - fhir client
      - SMART on FHIR
      - IHE
      - CDA
      - CCDA
      - openEHR
      - OMOP
      - interoperability
      - terminology server
      - value set
    "Data Platforms & ETL":
      - etl
      - extract transform load
      - data platform
      - data pipeline
      - warehouse
      - lakehouse
      - elt
      - airflow
      - dagster
      - prefect
      - dbt
      - kafka
      - spark
      - delta lake
    "Robotics & Surgical Systems":
      - robotics
      - robot
      - surgical robot
      - teleoperation
      - tele-operated
      - teleoperated
      - ros
      - manipulation
      - exoskeleton
      - surgical navigation
      - robotic surgery
    "Digital Therapeutics":
      - digital therapeutics
      - pdt
      - prescription digital therapeutics
      - samd
      - software as a medical device
      - cbt
      - behavior change
      - protocolized treatment
    "Privacy & Synthetic Data":
      - de-identification
      - deid
      - synthetic data
      - federated
      - federated learning
      - differential privacy
      - privacy-preserving
    "Digital Twins & Simulation":
      - digital twin
      - simulation
      - virtual trial
      - synthetic control arm
      - agent-based model
      - abm
    "Edge & Mobile Health AI":
      - on-device
      - edge ai
      - tinyml
      - tflite
      - coreml
      - mobile inference
      - on device
    "AR/VR & Training":
      - ar
      - vr
      - xr
      - simulator
      - haptics
    "Wearables & Remote Monitoring":
      - wearable
      - wearables
      - remote monitoring
      - rpm
      - smartwatch
      - fitness tracker
      - ecg
      - ppg
      - heart rate
      - sleep tracking
      - glucose monitoring
      - cgm
      - blood pressure
    "Public Health & Epidemiology":
      - public health
      - epidemiology
      - surveillance
      - outbreak
      - incidence
      - prevalence
      - vaccination
      - contact tracing
      - syndromic surveillance
      - seir
      - sir model
    "Genomics & Precision Medicine":
      - genomic
      - genomics
      - precision medicine
      - vcf
      - variant
      - bioinformatics
      - ngs
      - bam
      - sam
      - fastq
      - gff
      - annotation pipeline
      - variant calling
      - alignment
    "Mental Health":
      - mental health
      - psychiatry
      - psychology
      - therapy
      - depression
      - anxiety
      - cbt
      - mindfulness
      - mood tracking
      - suicide prevention
    "Patient Engagement & Scheduling":
      - scheduling
      - appointment
      - booking
      - patient portal
      - portal
      - calendar
      - check-in
      - reminder
      - waitlist
      - intake forms

# Set to true to validate config and skip GitHub API calls
# Turn off when you're ready to run live
dry_run: true
