name: Hector HealthTech Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv/bin/python -m pip install -r requirements.txt
      - name: Run Hector
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: .venv/bin/python scan_and_curate.py --live --limit 100 --log-level INFO
      - name: Run unit tests
        run: .venv/bin/python -m pytest -q
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PR_TOKEN }}
          commit-message: "chore: update curated healthtech list"
          title: "Update curated healthtech list (scheduled run)"
          body: |
            Automated update via Hector. Includes dated output and latest index.
          branch: hector/update-${{ github.run_id }}
          delete-branch: true
          add-paths: |
            result/healthtech-tools.md
            result/healthtech-tools-*.md
